production:
  adapter: postgresql
  database: ${postgresql_database}
  host: localhost
  username: ${postgresql_user}
  password: ${postgresql_password}
  encoding: utf8
  pool: 50

development:
  adapter: postgresql
  database: ${postgresql_database}
  host: localhost
  username: ${postgresql_user}
  password: ${postgresql_password}
  encoding: utf8
  pool: 50

test:
  adapter: postgresql
  database: ${postgresql_database_test}
  host: localhost
  username: ${postgresql_user}
  password: ${postgresql_password}
  encoding: utf8
  pool: 50
