export address_host=localhost
export address_port=
export address_path=/redmine
export apache_document_root=/var/www/html
export mail_from="redmine <redmine@example.net>"
export postgresql_database=redmine
export postgresql_database_test=redmine_test
export postgresql_user=redmine
export postgresql_password=redmine
export postgresql_version=10
export rvm_ruby=ruby-2.5.8
export smtp_tls=false
export smtp_server=localhost
export smtp_domain=example.com
export smtp_port=25
export smtp_authentication=plain
export smtp_username=redmine
export smtp_password=redmine
